# Generated by Django 3.0.8 on 2020-07-30 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('specialization', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=20)),
                ('practice_no', models.IntegerField()),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 30, 12, 51, 46, 534805))),
            ],
        ),
    ]
