# Generated by Django 3.1 on 2020-08-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0008_auto_20200811_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_register',
            name='image',
            field=models.ImageField(default='', upload_to='doctor_app/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 16, 47, 57, 487991)),
        ),
    ]
