# Generated by Django 3.1 on 2020-09-09 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0010_auto_20200817_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 19, 21, 45, 56561)),
        ),
    ]
