# Generated by Django 3.1 on 2020-09-09 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0011_auto_20200909_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 21, 3, 56, 615885)),
        ),
    ]
