# Generated by Django 3.0.8 on 2020-08-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Patient',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('email_to', models.CharField(max_length=100)),
                ('email_from', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=15)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 0, 39, 48, 30995))),
            ],
        ),
        migrations.CreateModel(
            name='Patient_register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(default='Null', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 0, 39, 48, 30995))),
            ],
        ),
    ]
