# Generated by Django 3.0.8 on 2020-08-10 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_patient',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 0, 56, 1, 782904)),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 0, 56, 1, 778921)),
        ),
    ]
