# Generated by Django 3.1 on 2020-08-17 16:48

import datetime
from django.db import migrations, models
import patient_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_auto_20200811_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=patient_app.models.upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient_register',
            name='image',
            field=models.ImageField(default='', upload_to='patient_app/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_patient',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 16, 47, 57, 494506)),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 16, 47, 57, 492368)),
        ),
    ]
