# Generated by Django 3.1 on 2020-09-09 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_auto_20200817_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_patient',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 19, 21, 45, 74281)),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 19, 21, 45, 73284)),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='image',
            field=models.ImageField(default='log.png', upload_to='patient_app/images'),
        ),
    ]
