# Generated by Django 3.1 on 2020-09-09 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_auto_20200909_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_patient',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 21, 8, 25, 737893)),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 21, 8, 25, 737069)),
        ),
    ]
