# Generated by Django 3.1 on 2020-09-11 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0008_auto_20200909_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_patient',
            name='color',
        ),
        migrations.RemoveField(
            model_name='booking_patient',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='booking_patient',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 3, 10, 16, 633149)),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 3, 10, 16, 628646)),
        ),
    ]
